import { chromium } from "playwright-core";
import chromiumBinary from "@sparticuz/chromium";
import path from "path";
import type { ScrapedOpportunity } from "./jaa";

// City of Jacksonville's real listings live on Oracle Fusion Cloud
// Procurement (Oracle ADF), not on rfp.coj.net — confirmed via direct
// fetch 2026-09-02: rfp.coj.net/rfp/solicitation/SolicitationDefault.asp
// is legacy classic-ASP, currently showing "No solicitations are
// Available." with a literal `Response.Write"..."` template bug leaking
// into the page output. That's not our bug, it's just confirmation the
// page is stale/unmaintained — treat it as dead, nothing scrapes it.
const COJ_URL = "https://eims.fa.us2.oraclecloud.com/fscmUI/faces/NegotiationAbstracts?prcBuId=300000008806179";
const SOURCE_AGENCY = "City of Jacksonville";

// Every "Details" link on the listing is an ADF commandLink
// (href="#", onclick-driven partial-page navigation), not a real
// bookmarkable per-row URL — clicking one would only ever produce a URL
// carrying the exact kind of session-scoped _afrLoop/_afrWindowId params
// this brief already flagged as unstable, so a "deep link" built that way
// wouldn't actually work in a later, different session anyway. source_url
// is the listing page itself for every row — the one link that's
// genuinely stable and where the client already showed us admins are
// expected to go to look something up (the page's own copy says a
// registered supplier has to log in to see full solicitation content).
//
// This page is JavaScript-rendered — confirmed via a bare fetch() 2026-09-02
// returning an empty shell with none of the solicitation rows in the raw
// HTML — so cheerio (jaa.ts's approach) can't work here; the table only
// exists after Oracle ADF finishes its client-side render. Using
// playwright-core + @sparticuz/chromium (not the full `playwright`
// package, whose bundled browser download is far over Vercel's ~50MB
// function size limit) to load a real headless Chromium, wait for actual
// network idle, then read the rendered DOM.
export async function scrapeCoj(): Promise<ScrapedOpportunity[]> {
  const executablePath = await chromiumBinary.executablePath();
  // Must be set before chromium.launch() reads it, and specifically via
  // process.env here rather than relying on it already being present —
  // @sparticuz/chromium's own docs flag that setting this too late (e.g.
  // only in the Vercel dashboard without also setting it here) is a real
  // cause of the "libnspr4.so" missing-shared-library failure in Lambda's
  // sandboxed filesystem.
  process.env.LD_LIBRARY_PATH = path.dirname(executablePath);

  const browser = await chromium.launch({
    args: chromiumBinary.args,
    executablePath,
    headless: true,
  });

  try {
    const page = await browser.newPage();
    page.setDefaultTimeout(30000);

    // Nothing here needs a real render (no screenshot, no visual layout) —
    // just the DOM after ADF's data fetch resolves. Blocking images/fonts/
    // media/stylesheets cuts load time meaningfully on a page this heavy
    // without losing anything the extraction below actually reads.
    await page.route("**/*", (route) => {
      const type = route.request().resourceType();
      if (type === "image" || type === "font" || type === "media" || type === "stylesheet") {
        return route.abort();
      }
      return route.continue();
    });

    await page.goto(COJ_URL, { waitUntil: "networkidle", timeout: 30000 });

    // "Search Results" is a real semantic attribute ADF assigns to its
    // result grid, confirmed unique on this page (exactly one match) —
    // deliberately not keyed off the surrounding CSS classes (e.g. "x1hg
    // x1i4" on the table itself, "xem"/"xen"/"x2ey" on rows/cells), which
    // are auto-generated by ADF's skin renderer and the more likely thing
    // to actually change if Oracle ever re-skins or upgrades this app —
    // exactly the "fragile to page structure changes" risk this brief
    // called out. summary="Search Results" is far more likely to survive
    // that than any of ADF's generated class hashes.
    const table = page.locator('table[summary="Search Results"]');
    await table.waitFor({ state: "attached", timeout: 30000 });

    const rows = await table.locator("tbody tr").evaluateAll((trs) =>
      trs.map((tr) => Array.from(tr.querySelectorAll("td")).map((td) => td.textContent?.trim() ?? ""))
    );

    const opportunities: ScrapedOpportunity[] = [];

    for (const cells of rows) {
      // Columns confirmed via direct inspection 2026-09-03: Solicitation
      // Number, Title, Type, Status, Posting Date, Open Date, Close Date,
      // Details (an icon-only link cell, always empty text).
      const [solicitationNumber, title, , status, , , closeDate] = cells;
      if (!title) continue;

      // Only "Active" is a real open opportunity to bid on — Closed,
      // Amended, and Awarded rows are all still returned by the same
      // query (this listing is a running log, not just open bids) and
      // would otherwise pollute matched_opportunities with things there's
      // nothing to do with. Amended is deliberately excluded too even
      // though it sounds active: on this page it means the amendment
      // itself needs review against whichever earlier row it amends, not
      // that this row is a fresh, unseen opportunity.
      if (status !== "Active") continue;

      opportunities.push({
        source_title: title,
        source_agency: SOURCE_AGENCY,
        source_url: COJ_URL,
        due_date: parseCojDate(closeDate),
        solicitation_number: solicitationNumber || null,
      });
    }

    return opportunities;
  } finally {
    await browser.close();
  }
}

// Listing shows "US Eastern Time" (page's own timezone label) as
// "9/17/26 9:58 AM" — M/D/YY h:mm AM/PM. Parsed as a plain local
// timestamp rather than precisely accounting for Eastern Time's exact
// UTC offset (which shifts with DST) — same tolerance jaa.ts already
// has for due_date (it leaves it null rather than guess); this is
// already strictly better than that, and an admin verifies the exact
// time by opening source_url regardless.
function parseCojDate(raw: string | undefined): string | null {
  if (!raw) return null;
  const match = raw.match(/^(\d{1,2})\/(\d{1,2})\/(\d{2})\s+(\d{1,2}):(\d{2})\s*(AM|PM)$/i);
  if (!match) return null;

  const [, monthStr, dayStr, yearStr, hourStr, minuteStr, meridiem] = match;
  const month = Number(monthStr);
  const day = Number(dayStr);
  const year = 2000 + Number(yearStr);
  let hour = Number(hourStr) % 12;
  if (meridiem.toUpperCase() === "PM") hour += 12;
  const minute = Number(minuteStr);

  const date = new Date(Date.UTC(year, month - 1, day, hour, minute));
  return Number.isNaN(date.getTime()) ? null : date.toISOString();
}
